baseURL: https://ninjasmosa.com
title: ninjasmosa.com
description: "Welcome to the official ninjasmosa website"
paginate: 20
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

languages:
    en:
        languageName: "English"
        weight: 1

taxonomies:
  category: categories
  tag: tags 

menu:
  main:
    - name: About me
      url: /aboutme
      weight: 5
    - name: Posts
      url: /posts
      weight: 10
    - name: Projects
      url: /projects
      weight: 15
    - name: Tutorials
      url: /tutorials
      weight: 20
#    - name: Art
#      url: /art
#      weight: 25
    - name: Archive
      url: /archive
      weight: 30
    - name: Search
      url: /search
      weight: 50

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary 

params:
    env: production
    author: ninjasmosa
    description: "Welcome to the official ninjasmosa website"
    site_description: "Welcome to the official ninjasmosa website"
    images:
    - /text1058.png
    defaultTheme: auto
    disableThemeToggle: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    ShowPostNavLinks: true
    Comments: true

    profileMode:
        enabled: true
        title: "ninjasmosa"
        subtitle: "Programmer + Gamer"
        imageUrl: "/download20220302164024.webp" # optional
#        imageTitle: "<title of image as alt>" # optional
        imageWidth: 360 # custom size
        imageHeight: 360 # custom size
        buttons:
          - name: About me
            url: /aboutme
          - name: Posts
            url: /posts
          - name: Projects
            url: /projects
          - name: Tutorials
            url: /tutorials
          - name: Donations
            url: /donations

    socialIcons:
        - name: mastodon
          url: "https://masto.ai/@ninjasmosa"
        - name: youtube
          url: "https://www.youtube.com/@ninjasmosa"
        - name: github
          url: "https://github.com/ninjasmosa"
        - name: itchio
          url: "https://ninjasmosa.itch.io/"
        - name: rss
          url: "rss"

module:
  mounts:
  - source: content
    target: content
  - source: static
    target: static
  - source: layouts
    target: layouts
  - source: data
    target: data
  - source: assets
    target: assets
  - source: i18n
    target: i18n
  - source: archetypes
    target: archetypes

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true

privacy:
    vimeo:
        disabled: false
        simple: false

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: false
