baseURL: http://ninjasmosa.com
title: ninjasmosa
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

languages:
    en:
        languageName: "English"
        weight: 1
        
menu:
  main:
    - name: About Me
      url: aboutme
      weight: 5
    - name: Archive
      url: archive
      weight: 10
    - name: NFTs
      url: nfts
      weight: 15
    - name: Carrd
      url: https://ninjasmosa.carrd.co
      weight: 20
    - name: Search
      url: search
      weight: 25


outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary 

params:
    env: production
    author: ninjasmosa
    defaultTheme: auto
    # disableThemeToggle: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    # comments: false

    homeInfoParams:
        Title: ninjasmosa official website
        Content: Greetings!

    socialIcons:
        - name: twitter
          url: "https://twitter.com/ninjasmosa"
        - name: youtube
          url: "https://www.youtube.com/channel/UCUU5vDID2lyUkTbeU4ry-CQ/"
        - name: github
          url: "https://github.com/ninjasmosa"
        - name: email
          url: "mailto:ninjasmosa@vivaldi.net"

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true

privacy:
    vimeo:
        disabled: false
        simple: false

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: false